// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9tReRSqAqF3saxupoV5PrmzEUQNcyuI8',
    appId: '1:980657959761:web:72a4a3cfbeed7990bed970',
    messagingSenderId: '980657959761',
    projectId: 'high-elo-zap',
    authDomain: 'high-elo-zap.firebaseapp.com',
    storageBucket: 'high-elo-zap.appspot.com',
    measurementId: 'G-31QMH4LCQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Eqk2WSoExRYajPYwYpSJ0t9MHV5wz-A',
    appId: '1:980657959761:android:1fdc2fa9e91bd009bed970',
    messagingSenderId: '980657959761',
    projectId: 'high-elo-zap',
    storageBucket: 'high-elo-zap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsTMITxrVME5IcevBbz5sL3JAkgPfy_0I',
    appId: '1:980657959761:ios:1c603d5b99aeea93bed970',
    messagingSenderId: '980657959761',
    projectId: 'high-elo-zap',
    storageBucket: 'high-elo-zap.appspot.com',
    iosClientId: '980657959761-du90op01nicg6n2pft7eb3radejg6640.apps.googleusercontent.com',
    iosBundleId: 'high.elo.app',
  );
}
